export const ETUDIANT_SIGNIN_REQUEST = "ETUDIANT_SIGNIN_REQUEST";
export const ETUDIANT_SIGNIN_SUCCESS = "ETUDIANT_SIGNIN_SUCCESS";
export const ETUDIANT_SIGNIN_FAIL = "ETUDIANT_SIGNIN_FAIL";

export const ETUDIANT_SIGNOUT = "ETUDIANT_SIGNOUT";
